name: Generate Keystore (run once)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore release.jks \
            -alias quickshare \
            -keyalg RSA -keysize 2048 \
            -validity 10000 \
            -storepass Undertaker098\
            -keypass Undertaker098 \
            -dname "CN=GameBooster, O=App, C=US"

      - name: Print base64
        run: |
          echo "====== KEYSTORE_BASE64 (copy everything between the lines) ======"
          base64 -w 0 release.jks
          echo ""
          echo "================================================================="
          echo "STORE_PASSWORD: Undertaker098"
          echo "KEY_ALIAS: gamebooster"
          echo "KEY_PASSWORD: Undertaker098"
